🔧 (extension-attach-artifact-release.yml): Refactor artifact download and copying process to handle failures more gracefully 🔧 (extension-attach-artifact-release.yml): Update artifact signing process to only sign new artifacts, not existing ones
🔧 (server.ts): update ASSET_DIR configuration to point to ./target directory

diff --git a/.github/workflows/extension-attach-artifact-release.yml b/.github/workflows/extension-attach-artifact-release.yml
--- a/.github/workflows/extension-attach-artifact-release.yml
+++ b/.github/workflows/extension-attach-artifact-release.yml
@@ -119,96 +119,96 @@ jobs:
           RELEASE_VERSION=$(mvn help:evaluate -Dexpression=project.version -q -DforceStdout)
           echo "RELEASE_VERSION=$RELEASE_VERSION" >> $GITHUB_ENV
 
-      - name: Check and download artifacts
+      - name: Check and download artifacts from GPM
         id: check-download-artifacts
         run: |
           mvn dependency:get -DgroupId=org.liquibase.ext -DartifactId=${{ github.event.repository.name }} -Dversion=${{ env.RELEASE_VERSION }} -Dtransitive=false || echo "Failed to download $extension artifact"
-          ARTIFACT_FOUND=$(ls -1 ~/.m2/repository/org/liquibase/ext/${{ github.event.repository.name }}/${{ env.RELEASE_VERSION }}/ | wc -l)
+          ARTIFACT_FOUND=$(ls -1 ~/.m2/repository/org/liquibase/ext/${{ github.event.repository.name }}/${{ env.RELEASE_VERSION }}/ 2>/dev/null | wc -l)
           echo "ARTIFACT_FOUND=$ARTIFACT_FOUND" >> $GITHUB_ENV
           if [ $ARTIFACT_FOUND -eq 0 ]; then
             echo "No artifact found"
           else
             echo "Artifact found"
             rm -rf ./target && mkdir -p ./target
-            mvn dependency:copy -Dartifact=org.liquibase.ext:${{ github.event.repository.name }}:${{ env.RELEASE_VERSION }}:jar -DoutputDirectory=./target
-            mvn dependency:copy -Dartifact=org.liquibase.ext:${{ github.event.repository.name }}:${{ env.RELEASE_VERSION }}:jar:sources -DoutputDirectory=./target
-            mvn dependency:copy -Dartifact=org.liquibase.ext:${{ github.event.repository.name }}:${{ env.RELEASE_VERSION }}:jar:javadoc -DoutputDirectory=./target
-            mvn dependency:copy -Dartifact=org.liquibase.ext:${{ github.event.repository.name }}:${{ env.RELEASE_VERSION }}:pom -DoutputDirectory=./target
-            ls -ltr ./target
+            mvn dependency:copy -Dartifact=org.liquibase.ext:${{ github.event.repository.name }}:${{ env.RELEASE_VERSION }}:jar -DoutputDirectory=./target || echo "Failed to copy $extension artifact"
+            mvn dependency:copy -Dartifact=org.liquibase.ext:${{ github.event.repository.name }}:${{ env.RELEASE_VERSION }}:jar:sources -DoutputDirectory=./target || echo "Failed to copy $extension sources"
+            mvn dependency:copy -Dartifact=org.liquibase.ext:${{ github.event.repository.name }}:${{ env.RELEASE_VERSION }}:jar:javadoc -DoutputDirectory=./target || echo "Failed to copy $extension javadoc"
+            mvn dependency:copy -Dartifact=org.liquibase.ext:${{ github.event.repository.name }}:${{ env.RELEASE_VERSION }}:pom -DoutputDirectory=./target || echo "Failed to copy $extension POM file"
           fi
 
-      # - name: Get latest draft release ID
-      #   id: get-release
-      #   run: |
-      #     LATEST_DRAFT_RELEASE=$(curl -X GET -H "Authorization: token ${{ secrets.BOT_TOKEN }}" "https://api.github.com/repos/${{ github.repository }}/releases?per_page=1" | jq -r 'if .[].draft == true then .[].id else empty end')
-      #     echo "Latest Draft Release ID: $LATEST_DRAFT_RELEASE"
-      #     echo "RELEASE_ID=$LATEST_DRAFT_RELEASE" >> $GITHUB_ENV
+      - name: Get latest draft release ID
+        id: get-release
+        run: |
+          LATEST_DRAFT_RELEASE=$(curl -X GET -H "Authorization: token ${{ secrets.BOT_TOKEN }}" "https://api.github.com/repos/${{ github.repository }}/releases?per_page=1" | jq -r 'if .[].draft == true then .[].id else empty end')
+          echo "Latest Draft Release ID: $LATEST_DRAFT_RELEASE"
+          echo "RELEASE_ID=$LATEST_DRAFT_RELEASE" >> $GITHUB_ENV
 
-      # - name: List artifacts in release
-      #   if: env.RELEASE_ID != '' && env.RELEASE_ID != null
-      #   id: list-artifacts
-      #   run: |
-      #     RELEASE_ID="${{ env.RELEASE_ID }}"
-      #     ARTIFACTS=$(curl -X GET -H "Authorization: token ${{ secrets.BOT_TOKEN }}" "https://api.github.com/repos/${{ github.repository }}/releases/$RELEASE_ID/assets" | jq -r '.[].id')
-      #     echo "Artifacts to delete: $ARTIFACTS"
-      #     ARTIFACTS_CLEANED=$(echo "$ARTIFACTS" | tr -s '[:space:]' ',' | sed 's/,$//')
-      #     echo "ARTIFACTS_TO_DELETE=$ARTIFACTS_CLEANED" >> $GITHUB_ENV
+      - name: List artifacts in release
+        if: env.RELEASE_ID != '' && env.RELEASE_ID != null
+        id: list-artifacts
+        run: |
+          RELEASE_ID="${{ env.RELEASE_ID }}"
+          ARTIFACTS=$(curl -X GET -H "Authorization: token ${{ secrets.BOT_TOKEN }}" "https://api.github.com/repos/${{ github.repository }}/releases/$RELEASE_ID/assets" | jq -r '.[].id')
+          echo "Artifacts to delete: $ARTIFACTS"
+          ARTIFACTS_CLEANED=$(echo "$ARTIFACTS" | tr -s '[:space:]' ',' | sed 's/,$//')
+          echo "ARTIFACTS_TO_DELETE=$ARTIFACTS_CLEANED" >> $GITHUB_ENV
 
-      # - name: Delete artifacts
-      #   if: env.ARTIFACTS_TO_DELETE != null
-      #   run: |
-      #     RELEASE_ID="${{ env.RELEASE_ID }}"
-      #     ARTIFACTS_TO_DELETE="${{ env.ARTIFACTS_TO_DELETE }}"
-      #     IFS=',' read -ra values <<< "$ARTIFACTS_TO_DELETE"
-      #     for value in "${values[@]}"; do
-      #       curl -X DELETE -H "Authorization: token ${{ secrets.BOT_TOKEN }}" "https://api.github.com/repos/${{ github.repository }}/releases/assets/$value"
-      #       echo "Deleted artifact ID: $value"
-      #     done
+      - name: Delete artifacts
+        if: env.ARTIFACTS_TO_DELETE != null
+        run: |
+          RELEASE_ID="${{ env.RELEASE_ID }}"
+          ARTIFACTS_TO_DELETE="${{ env.ARTIFACTS_TO_DELETE }}"
+          IFS=',' read -ra values <<< "$ARTIFACTS_TO_DELETE"
+          for value in "${values[@]}"; do
+            curl -X DELETE -H "Authorization: token ${{ secrets.BOT_TOKEN }}" "https://api.github.com/repos/${{ github.repository }}/releases/assets/$value"
+            echo "Deleted artifact ID: $value"
+          done
 
-      # - name: Import GPG key
-      #   id: import_gpg
-      #   uses: crazy-max/ghaction-import-gpg@v6
-      #   with:
-      #     gpg_private_key: ${{ secrets.GPG_SECRET }}
-      #     passphrase: ${{ secrets.GPG_PASSPHRASE }}
+      - name: Import GPG key
+        id: import_gpg
+        uses: crazy-max/ghaction-import-gpg@v6
+        with:
+          gpg_private_key: ${{ secrets.GPG_SECRET }}
+          passphrase: ${{ secrets.GPG_PASSPHRASE }}
 
-      # - name: Sign Files for Draft Release
-      #   if: env.ARTIFACT_FOUND == 'false'
-      #   run: |
-      #     gpg -K
-      #     version=$(mvn help:evaluate -Dexpression=project.version -q -DforceStdout)
-      #     ./.github/sign_artifact.sh ./target/${{ env.artifact_id }}-${version}.jar
-      #     ./.github/sign_artifact.sh ./target/${{ env.artifact_id }}-${version}.pom
-      #     ./.github/sign_artifact.sh ./target/${{ env.artifact_id }}-${version}-javadoc.jar
-      #     ./.github/sign_artifact.sh ./target/${{ env.artifact_id }}-${version}-sources.jar
+      - name: Sign Files for Draft Release
+        # Existing GPM artifacts are already signed
+        if: env.ARTIFACT_FOUND == 0
+        run: |
+          gpg -K
+          version=$(mvn help:evaluate -Dexpression=project.version -q -DforceStdout)
+          ./.github/sign_artifact.sh ./target/${{ env.artifact_id }}-${version}.jar
+          ./.github/sign_artifact.sh ./target/${{ env.artifact_id }}-${version}.pom
+          ./.github/sign_artifact.sh ./target/${{ env.artifact_id }}-${version}-javadoc.jar
+          ./.github/sign_artifact.sh ./target/${{ env.artifact_id }}-${version}-sources.jar
 
-      # - name: Set draft release title
-      #   id: set-release-title
-      #   run: |
-      #     version=$(mvn help:evaluate -Dexpression=project.version -q -DforceStdout)
-      #     RELEASE_TITLE="v$version"
-      #     echo "Updating release title to $RELEASE_TITLE"
-      #     curl -X PATCH -H "Accept: application/vnd.github+json" -H "X-GitHub-Api-Version: 2022-11-28" -H "Authorization: Bearer ${{ secrets.BOT_TOKEN }}" -d '{"name": "'"$RELEASE_TITLE"'"}' "https://api.github.com/repos/${{ github.repository }}/releases/${{ env.RELEASE_ID }}"
+      - name: Set draft release title
+        id: set-release-title
+        run: |
+          version=$(mvn help:evaluate -Dexpression=project.version -q -DforceStdout)
+          RELEASE_TITLE="v$version"
+          echo "Updating release title to $RELEASE_TITLE"
+          curl -X PATCH -H "Accept: application/vnd.github+json" -H "X-GitHub-Api-Version: 2022-11-28" -H "Authorization: Bearer ${{ secrets.BOT_TOKEN }}" -d '{"name": "'"$RELEASE_TITLE"'"}' "https://api.github.com/repos/${{ github.repository }}/releases/${{ env.RELEASE_ID }}"
 
-      # - name: Attach Files to Draft Release
-      #   id: upload-release-asset
-      #   run: ./.github/upload_asset.sh $(mvn help:evaluate -Dexpression=project.version -q -DforceStdout)
-      #   env:
-      #     GITHUB_TOKEN: ${{ secrets.BOT_TOKEN }}
-      #     ASSET_NAME_PREFIX: "${{ env.artifact_id }}-"
-      #     ASSET_DIR: ./target
+      - name: Attach Files to Draft Release
+        id: upload-release-asset
+        run: ./.github/upload_asset.sh $(mvn help:evaluate -Dexpression=project.version -q -DforceStdout)
+        env:
+          GITHUB_TOKEN: ${{ secrets.BOT_TOKEN }}
+          ASSET_NAME_PREFIX: "${{ env.artifact_id }}-"
+          ASSET_DIR: ./target
 
-      # - name: Get upload_zip.sh Script File
-      #   if: inputs.zip == 'true'
-      #   run: |
-      #     curl -o $PWD/.github/upload_zip.sh https://raw.githubusercontent.com/liquibase/build-logic/v0.7.8/.github/upload_zip.sh
-      #     chmod +x $PWD/.github/upload_zip.sh
+      - name: Get upload_zip.sh Script File
+        if: inputs.zip == 'true'
+        run: |
+          curl -o $PWD/.github/upload_zip.sh https://raw.githubusercontent.com/liquibase/build-logic/v0.7.8/.github/upload_zip.sh
+          chmod +x $PWD/.github/upload_zip.sh
   
-      # - name: Attach Zip File to Draft Release
-      #   if: inputs.zip == 'true'
-      #   id: upload-release-zip
-      #   run: ./.github/upload_zip.sh $(mvn help:evaluate -Dexpression=project.version -q -DforceStdout)
-      #   env:
-      #     GITHUB_TOKEN: ${{ secrets.BOT_TOKEN }}
-      #     ASSET_NAME_PREFIX: "${{ env.artifact_id }}-"
-      #     ASSET_DIR: ./target
+      - name: Attach Zip File to Draft Release
+        if: inputs.zip == 'true'
+        id: upload-release-zip
+        run: ./.github/upload_zip.sh $(mvn help:evaluate -Dexpression=project.version -q -DforceStdout)
+        env:
+          GITHUB_TOKEN: ${{ secrets.BOT_TOKEN }}
+          ASSET_NAME_PREFIX: "${{ env.artifact_id }}-"
+          ASSET_DIR: ./target
