🔧 (extension-attach-artifact-release.yml): Use environment variable ARTIFACT_NAME to store the repository name for better readability and consistency in artifact handling.

diff --git a/.github/workflows/extension-attach-artifact-release.yml b/.github/workflows/extension-attach-artifact-release.yml
--- a/.github/workflows/extension-attach-artifact-release.yml
+++ b/.github/workflows/extension-attach-artifact-release.yml
@@ -121,19 +121,21 @@ jobs:
 
       - name: Check and download artifacts from GPM
         id: check-download-artifacts
+        env:
+          ARTIFACT_NAME: ${{ github.event.repository.name }}
         run: |
-          mvn dependency:get -DgroupId=org.liquibase.ext -DartifactId=${{ github.event.repository.name }} -Dversion=${{ env.RELEASE_VERSION }} -Dtransitive=false || echo "Failed to download $extension artifact"
-          ARTIFACT_FOUND=$(ls -1 ~/.m2/repository/org/liquibase/ext/${{ github.event.repository.name }}/${{ env.RELEASE_VERSION }}/ 2>/dev/null | wc -l)
+          mvn dependency:get -DgroupId=org.liquibase.ext -DartifactId=${{ env.ARTIFACT_NAME }} -Dversion=${{ env.RELEASE_VERSION }} -Dtransitive=false || echo "Failed to download $extension artifact"
+          ARTIFACT_FOUND=$(ls -1 ~/.m2/repository/org/liquibase/ext/${{ env.ARTIFACT_NAME }}/${{ env.RELEASE_VERSION }}/ 2>/dev/null | wc -l)
           echo "ARTIFACT_FOUND=$ARTIFACT_FOUND" >> $GITHUB_ENV
           if [ $ARTIFACT_FOUND -eq 0 ]; then
             echo "No artifact found"
           else
             echo "Artifact found"
             rm -rf ./target && mkdir -p ./target
-            mvn dependency:copy -Dartifact=org.liquibase.ext:${{ github.event.repository.name }}:${{ env.RELEASE_VERSION }}:jar -DoutputDirectory=./target || echo "Failed to copy $extension artifact"
-            mvn dependency:copy -Dartifact=org.liquibase.ext:${{ github.event.repository.name }}:${{ env.RELEASE_VERSION }}:jar:sources -DoutputDirectory=./target || echo "Failed to copy $extension sources"
-            mvn dependency:copy -Dartifact=org.liquibase.ext:${{ github.event.repository.name }}:${{ env.RELEASE_VERSION }}:jar:javadoc -DoutputDirectory=./target || echo "Failed to copy $extension javadoc"
-            mvn dependency:copy -Dartifact=org.liquibase.ext:${{ github.event.repository.name }}:${{ env.RELEASE_VERSION }}:pom -DoutputDirectory=./target || echo "Failed to copy $extension POM file"
+            mvn dependency:copy -Dartifact=org.liquibase.ext:${{ env.ARTIFACT_NAME }}:${{ env.RELEASE_VERSION }}:jar -DoutputDirectory=./target || echo "Failed to copy $extension artifact"
+            mvn dependency:copy -Dartifact=org.liquibase.ext:${{ env.ARTIFACT_NAME }}:${{ env.RELEASE_VERSION }}:jar:sources -DoutputDirectory=./target || echo "Failed to copy $extension sources"
+            mvn dependency:copy -Dartifact=org.liquibase.ext:${{ env.ARTIFACT_NAME }}:${{ env.RELEASE_VERSION }}:jar:javadoc -DoutputDirectory=./target || echo "Failed to copy $extension javadoc"
+            mvn dependency:copy -Dartifact=org.liquibase.ext:${{ env.ARTIFACT_NAME }}:${{ env.RELEASE_VERSION }}:pom -DoutputDirectory=./target || echo "Failed to copy $extension POM file"
           fi
 
       - name: Get latest draft release ID
