chore(fossa_ai.yml): refactor FOSSA Snippets Detection Decoration workflow to run on job failure and include additional information in the comment output

diff --git a/.github/workflows/fossa_ai.yml b/.github/workflows/fossa_ai.yml
--- a/.github/workflows/fossa_ai.yml
+++ b/.github/workflows/fossa_ai.yml
@@ -47,6 +47,42 @@ jobs:
       run: |
         # https://github.com/fossas/fossa-cli/blob/master/docs/references/subcommands/snippets/analyze.md
         fossa snippets analyze -o snippets 2>&1 | tee snippets.out
+        # fail the job if snippets.out does not contain '0 matches'
+        if ! grep -q '0 matches' snippets.out; then
+          exit 1
+        fi
+
+    - name: FOSSA Snippets Detection Decoration
+      if: failure() && ${{ inputs.check_snippets }}
+      uses: actions/github-script@v6
+      continue-on-error: true        
+      with:
+        github-token: ${{ secrets.GITHUB_TOKEN }}
+        script: |
+          const run_url = process.env.GITHUB_SERVER_URL + '/' + process.env.GITHUB_REPOSITORY + '/actions/runs/' + process.env.GITHUB_RUN_ID
+          const run_link = '<a href="' + run_url + '">Actions</a>.'
+          const fs = require('fs')
+          const snippets_file = fs.readFileSync('snippets.out', 'utf8')
+          const snippets = snippets_file.length > 65000 ? snippets_file.toString().substring(0, 65000) + " ..." : snippets_file
+          const truncated_message = snippets_file.length > 65000 ? "Output is too long and was truncated. You can read full log in " + run_link + "<br /><br />" : ""
+          const output = `#### FOSSA Snippets Detection 🤖\`${{ steps.snippets.outcome }}\`
+          <details><summary>Snippets Detection Output</summary>
+
+          \`\`\`\n
+          ${snippets}
+          \`\`\`
+
+          </details>
+          ${truncated_message}
+
+          *Pusher: @${{ github.actor }}, Action: \`${{ github.event_name }}\`, Working Directory: \`${{ github.workspace }}\`, Workflow: \`${{ github.workflow }}\`*`;
+            
+          github.rest.issues.createComment({
+            issue_number: context.issue.number,
+            owner: context.repo.owner,
+            repo: context.repo.repo,
+            body: output
+          })
 
     - name: Generate Snippet Dependencies
       if: ${{ inputs.check_snippets }}
@@ -79,38 +115,6 @@ jobs:
       run: |
         # https://github.com/fossas/fossa-cli/tree/master/docs/references/subcommands/test
         fossa test 2>&1 | tee test.out
-
-    - name: FOSSA Snippets Detection Decoration
-      if: github.event_name == 'pull_request' && ${{ inputs.check_snippets }}
-      uses: actions/github-script@v6
-      continue-on-error: true        
-      with:
-        github-token: ${{ secrets.GITHUB_TOKEN }}
-        script: |
-          const run_url = process.env.GITHUB_SERVER_URL + '/' + process.env.GITHUB_REPOSITORY + '/actions/runs/' + process.env.GITHUB_RUN_ID
-          const run_link = '<a href="' + run_url + '">Actions</a>.'
-          const fs = require('fs')
-          const snippets_file = fs.readFileSync('snippets.out', 'utf8')
-          const snippets = snippets_file.length > 65000 ? snippets_file.toString().substring(0, 65000) + " ..." : snippets_file
-          const truncated_message = snippets_file.length > 65000 ? "Output is too long and was truncated. You can read full log in " + run_link + "<br /><br />" : ""
-          const output = `#### FOSSA Snippets Detection 🤖\`${{ steps.snippets.outcome }}\`
-          <details><summary>Snippets Detection Output</summary>
-
-          \`\`\`\n
-          ${snippets}
-          \`\`\`
-
-          </details>
-          ${truncated_message}
-
-          *Pusher: @${{ github.actor }}, Action: \`${{ github.event_name }}\`, Working Directory: \`${{ github.workspace }}\`, Workflow: \`${{ github.workflow }}\`*`;
-            
-          github.rest.issues.createComment({
-            issue_number: context.issue.number,
-            owner: context.repo.owner,
-            repo: context.repo.repo,
-            body: output
-          })
 
     - name: FOSSA Test Decoration
       if: github.event_name == 'pull_request'
