add generate-oss-pro-fossa-reports.

diff --git a/.github/workflows/fossa_ai.yml b/.github/workflows/fossa_ai.yml
--- a/.github/workflows/fossa_ai.yml
+++ b/.github/workflows/fossa_ai.yml
@@ -28,6 +28,7 @@ jobs:
   fossa-scan:
     runs-on: ubuntu-latest
     permissions: write-all
+    if: github.event_name != 'repository_dispatch'
     env:
       FOSSA_API_KEY: ${{ secrets.FOSSA_API_KEY }}
 
@@ -138,14 +139,68 @@ jobs:
         if: ${{ inputs.generate_sbom }}
         run: |
           # https://github.com/fossas/fossa-cli/blob/master/docs/references/subcommands/report.md
-          fossa report -p ${{ github.event.repository.name }} attribution --format json 2>&1 | tee sbom.json
+          fossa report -p ${{ github.event.repository.name }} attribution --format html 2>&1 | tee sbom.html
 
       - name: Archive FOSSA SBOM Report
         if: ${{ inputs.generate_sbom }}
         uses: actions/upload-artifact@v4
         with:
           name: sbom
-          path: sbom.json
+          path: sbom.html
+
+    generate-oss-pro-fossa-reports:
+      runs-on: ubuntu-latest
+      permissions: write-all
+      if: github.event_name == 'repository_dispatch'
+      env:
+        FOSSA_API_KEY: ${{ secrets.FOSSA_API_KEY }}
+        AWS_ACCESS_KEY_ID: ${{ secrets.LIQUIBASEORIGIN_ACCESS_KEY_ID }}
+        AWS_SECRET_ACCESS_KEY: ${{ secrets.LIQUIBASEORIGIN_SECRET_ACCESS_KEY }}
+        AWS_DEFAULT_REGION: us-east-1
+      steps:
+
+      - name: Checkout Code
+        uses: actions/checkout@v4
+
+      - name: Install FOSSA CLI
+        run: |
+          curl -H 'Cache-Control: no-cache' https://raw.githubusercontent.com/fossas/fossa-cli/master/install-latest.sh | bash
+          
+      - name: Run FOSSA Analyze
+        id: analyze
+        run: |
+          # https://github.com/fossas/fossa-cli/tree/master/docs/references/subcommands/analyze
+          # Run the full analyze on the current branch to be checked by the test command
+          fossa analyze -p ${{ github.event.repository.name }} -b ${{ github.head_ref || github.ref_name }} 2>&1 | tee analyze_no_ai.out
+
+          - name: Run FOSSA Test
+            id: test
+            run: |
+              # https://github.com/fossas/fossa-cli/tree/master/docs/references/subcommands/test
+              fossa test -p ${{ github.event.repository.name }} 2>&1 | tee test.out
+              FILE="test.out"
+              if [ -f "$FILE" ]; then
+                  if grep -q "Test passed" "$FILE"; then
+                      echo "The file '$FILE' contains 'Test passed'."
+                  else
+                      echo "The file '$FILE' does not contain 'Test passed'."
+                      exit 1
+                  fi
+              else
+                  echo "Error: The file '$FILE' does not exist."
+              fi
+
+      - name: Run FOSSA SBOM Report
+        run: |
+          # https://github.com/fossas/fossa-cli/blob/master/docs/references/subcommands/report.md
+          fossa report -p ${{ github.event.repository.name }} attribution --format cyclonedx-json 2>&1 | tee sbom.cyclonedx-json
+
+          - name: Archive FOSSA SBOM Report
+            if: ${{ inputs.generate_sbom }}
+            uses: actions/upload-artifact@v4
+            with:
+              name: sbom
+              path: sbom.cyclonedx-json
 
       - name: Get current timestamp
         id: timestamp
@@ -154,4 +209,4 @@ jobs:
       - name: Upload FOSSA Results to s3 for Liquibase releases
         if: github.event.action == 'oss-released-version'
         run: |
-          aws s3 cp sbom.json s3://liquibase-artifacts/fossa/liquibase-pro-${{ inputs.latest_version }}_${{ env.timestamp }}/sbom.json
+          aws s3 cp sbom.cyclonedx-json s3://liquibaseorg-origin/sbom-lb-lbpro-releases/liquibase-pro-${{ inputs.latest_version }}_${{ env.timestamp }}/sbom.cyclonedx-json
