fix(fossa_ai.yml): add error handling to check if output files exist and contain expected content to improve workflow reliability and error reporting

diff --git a/.github/workflows/fossa_ai.yml b/.github/workflows/fossa_ai.yml
--- a/.github/workflows/fossa_ai.yml
+++ b/.github/workflows/fossa_ai.yml
@@ -47,6 +47,17 @@ jobs:
       run: |
         # https://github.com/fossas/fossa-cli/blob/master/docs/references/subcommands/snippets/analyze.md
         fossa snippets analyze -o snippets 2>&1 | tee snippets.out
+        FILE="snippets.out"
+        if [ -f "$FILE" ]; then
+            if grep -q "0 matches" "$FILE"; then
+                echo "The file '$FILE' contains '0 matches'."
+            else
+                echo "The file '$FILE' does not contain '0 matches'."
+                exit 1
+            fi
+        else
+            echo "Error: The file '$FILE' does not exist."
+        fi
 
     - name: Generate Snippet Dependencies
       if: ${{ inputs.check_snippets }}
@@ -79,6 +90,17 @@ jobs:
       run: |
         # https://github.com/fossas/fossa-cli/tree/master/docs/references/subcommands/test
         fossa test 2>&1 | tee test.out
+        FILE="test.out"
+        if [ -f "$FILE" ]; then
+            if grep -q "Test passed" "$FILE"; then
+                echo "The file '$FILE' contains 'Test passed'."
+            else
+                echo "The file '$FILE' does not contain 'Test passed'."
+                exit 1
+            fi
+        else
+            echo "Error: The file '$FILE' does not exist."
+        fi
 
     - name: Label PR with AI label
       if: ${{ inputs.check_ai_generated_code }}
