add option for liquibase org

diff --git a/.github/workflows/fossa.yml b/.github/workflows/fossa.yml
--- a/.github/workflows/fossa.yml
+++ b/.github/workflows/fossa.yml
@@ -1,5 +1,5 @@
 # Name of the GitHub Action workflow
-name: FOSSA Report Generation - Datical Repsoitories
+name: FOSSA Report Generation
 
 # Event triggers for the workflow
 on:
@@ -10,6 +10,10 @@ on:
         required: false
         type: boolean
         description: 'Flag to specify if the project uses Gradle instead of Maven'
+      org:
+        required: false
+        type: string
+        description: 'Organization name: liquibase or datical'
   release:
     types: [published] # Run this action when a release is published
 
@@ -26,6 +30,7 @@ jobs:
         uses: actions/checkout@v4
 
       - name: Set up JDK
+        if: ${{ github.event.inputs.org == 'datical' }}
         uses: actions/setup-java@v4
         with:
           distribution: 'temurin'
@@ -36,20 +41,74 @@ jobs:
           server-password: REPO_MAVEN_PASSWORD
 
       - name: Install Maven dependencies (excluding test scope)
-        if: ${{ github.event.inputs.gradle == 'false' }}
+        if: ${{ github.event.inputs.gradle == 'false' && github.event.inputs.org == 'datical'}}
         run: mvn -B -U -DskipTests -ntp clean install
         env:
           REPO_MAVEN_USER: ${{ secrets.REPO_MAVEN_USER }}
           REPO_MAVEN_PASSWORD: ${{ secrets.REPO_MAVEN_PASSWORD }}
 
       - name: Install Gradle dependencies
-        if: ${{ github.event.inputs.gradle == 'true' }}
+        if: ${{ github.event.inputs.gradle == 'true' && github.event.inputs.org == 'datical'}}
         run: |
           chmod +x gradlew
           ./gradlew clean build -x test
         env:
           REPO_MAVEN_USER: ${{ secrets.REPO_MAVEN_USER }}
           REPO_MAVEN_PASSWORD: ${{ secrets.REPO_MAVEN_PASSWORD }}
+
+
+      - name: Set up JDK
+        if: ${{ github.event.inputs.org == 'liquibase' }}
+        uses: actions/setup-java@v4
+        with:
+          distribution: 'temurin'
+          java-version: '17'
+
+            #look for dependencies in maven
+      - name: maven-settings-xml-action
+        if: ${{ github.event.inputs.org == 'liquibase' }}
+        uses: whelk-io/maven-settings-xml-action@v22
+        with:
+          repositories: |
+            [
+              {
+                "id": "liquibase",
+                "url": "https://maven.pkg.github.com/liquibase/liquibase",
+                "releases": {
+                  "enabled": "false"
+                },
+                "snapshots": {
+                  "enabled": "true",
+                  "updatePolicy": "always"
+                }
+              },
+              {
+                "id": "liquibase-pro",
+                "url": "https://maven.pkg.github.com/liquibase/liquibase-pro",
+                "releases": {
+                  "enabled": "false"
+                },
+                "snapshots": {
+                  "enabled": "true",
+                  "updatePolicy": "always"
+                }
+              }
+            ]
+          servers: |
+            [
+              {
+                "id": "liquibase-pro",
+                "username": "liquibot",
+                "password": "${{ secrets.LIQUIBOT_PAT }}"
+              },
+              {
+                "id": "liquibase",
+                "username": "liquibot",
+                "password": "${{ secrets.LIQUIBOT_PAT }}"
+              }
+            ]
+            
+            
 
       - name: run FOSSA CLI
         uses: fossas/fossa-action@main
@@ -62,16 +121,30 @@ jobs:
         run: |
           commit_sha=`(git rev-parse HEAD)`
           echo "commit_sha=${commit_sha}" >> $GITHUB_OUTPUT
+
       - name: Get repository name
         id: get_repo_name
         run: echo "repo_name=$(echo ${{ github.repository }} | cut -d'/' -f2)" >> $GITHUB_OUTPUT
 
       # https://docs.fossa.com/docs/download-fossa-project-attribution-reports
       -   name: Set the dependency metadata information
+          if: ${{ github.event.inputs.org == 'datical'}}
           run: |
             sleep 120
             mkdir /home/runner/work/${{ steps.get_repo_name.outputs.repo_name }}/fossa_reports
             curl --location 'https://app.fossa.com/api/revisions/custom%2B40163%2Fgithub.com%2FDatical%2F${{ steps.get_repo_name.outputs.repo_name }}%24${{ steps.get_commit_sha.outputs.commit_sha }}/attribution/download?format=CSV&includeDirectDependencies=true&includeDeepDependencies=false&download=true' \
+            --header 'Authorization: Bearer ${{ secrets.FOSSA_COMBINED_REPORT }}' \
+            -o /home/runner/work/${{ steps.get_repo_name.outputs.repo_name }}/fossa_reports/${{ steps.get_repo_name.outputs.repo_name }}.csv
+            ls -l /home/runner/work/${{ steps.get_repo_name.outputs.repo_name }}/fossa_reports
+            cat /home/runner/work/${{ steps.get_repo_name.outputs.repo_name }}/fossa_reports/${{ steps.get_repo_name.outputs.repo_name }}.csv || echo "File is empty or not found"
+
+
+      -   name: Set the dependency metadata information
+          if: ${{ github.event.inputs.org == 'liquibase'}}
+          run: |
+            sleep 120
+            mkdir /home/runner/work/${{ steps.get_repo_name.outputs.repo_name }}/fossa_reports
+            curl --location 'https://app.fossa.com/api/revisions/custom%2B40163%2Fgithub.com%2Fliquibase%2F${{ steps.get_repo_name.outputs.repo_name }}%24${{ steps.get_commit_sha.outputs.commit_sha }}/attribution/download?format=CSV&includeDirectDependencies=true&includeDeepDependencies=false&download=true' \
             --header 'Authorization: Bearer ${{ secrets.FOSSA_COMBINED_REPORT }}' \
             -o /home/runner/work/${{ steps.get_repo_name.outputs.repo_name }}/fossa_reports/${{ steps.get_repo_name.outputs.repo_name }}.csv
             ls -l /home/runner/work/${{ steps.get_repo_name.outputs.repo_name }}/fossa_reports
@@ -85,6 +158,7 @@ jobs:
       #                  AWS_ACCESS_KEY_ID: ${{ secrets.LIQUIBASEORIGIN_ACCESS_KEY_ID }}
       #                  AWS_SECRET_ACCESS_KEY: ${{ secrets.LIQUIBASEORIGIN_SECRET_ACCESS_KEY }}
       #                  AWS_DEFAULT_REGION: us-east-1
+
 
       - name : Upload to build page
         uses: actions/upload-artifact@v3
